---
- name: Install GarageBand via Mac App Store
  command: mas install "{{ item.id }}"
  args:
    creates: /Applications/{{ item.name }}.app
  with_items:
    - { id: 682658836, name: "GarageBand" }
  when: ansible_os_family == "Darwin"
